name: Test slack message

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Post to a Slack channel on failure
        if: always() && job.status != 'success'
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04KXEF19PX'
          slack-message: "Pipeline failed (status: ${{ job.status }})"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}