name: Test slack message

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04KXEF19PX'
          # For posting a simple plain text message
          slack-message: "Hello world! ${{ job.status }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}